<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Regression Test Suite__PR_JY_002"
           tests="6"
           failures="2"
           errors="0"
           skipped="4"
           time="1.035">
  <properties />
            <testcase name="tearDown" time="0.000" classname="com.automation.login.logindemo">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.automation.utilites.BaseTest.tearDown(BaseTest.java:78)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:756)
  org.testng.TestRunner.run(TestRunner.java:610)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
  org.testng.TestNG.runSuites(TestNG.java:1133)
  org.testng.TestNG.run(TestNG.java:1104)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
            <testcase name="PR_JY_002_ValidateName_001" time="1.022" classname="com.automation.login.logindemo">
                <failure type="org.testng.internal.thread.ThreadTimeoutException"
                  message="Method com.automation.login.logindemo.PR_JY_002_ValidateName_001() didn&apos;t finish within the time-out 1000"
              >
<![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.automation.login.logindemo.PR_JY_002_ValidateName_001() didn't finish within the time-out 1000
  java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
            <testcase name="tearDown" time="0.0" classname="com.automation.login.logindemo">
          <skipped />
    </testcase>
            <testcase name="tearDown" time="0.0" classname="com.automation.login.logindemo">
          <skipped />
    </testcase>
            <testcase name="PR_JY__002_ValidateAge_003" time="0.0" classname="com.automation.login.logindemo">
          <skipped />
    </testcase>
            <testcase name="PR_JY_002_ValidateName_002" time="0.0" classname="com.automation.login.logindemo">
          <skipped />
    </testcase>
  
  
</testsuite>
